main = ".open-next/worker.js"
name = "applyo-frontend"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# Service binding to the applyo-worker
[[services]]
binding = "APPLYO_WORKER"
service = "applyo-worker"