# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "applyo-worker"
main = "src/index.ts"
compatibility_date = "2025-10-11"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "applyo-db"
database_id = "f1c25a1c-ba2f-46e7-89f4-a6d632690141"
migrations_dir = "drizzle"
remote = true

[dev]
port = 8787

[[durable_objects.bindings]]
name = "Prospects"
class_name = "Prospects"

[[durable_objects.bindings]]
name = "Profiler"
class_name = "Profiler"

[[durable_objects.bindings]]
name = "PeopleFinder"
class_name = "PeopleFinder"

[[durable_objects.bindings]]
name = "EmailFinder"
class_name = "EmailFinder"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Prospects"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["Profiler"]

[[migrations]]
tag = "v3"
new_sqlite_classes = ["PeopleFinder"]

[[migrations]]
tag = "v4"
new_sqlite_classes = ["EmailFinder"]

# Secrets (use `wrangler secret put TAVILY_API_KEY` to set)
# TAVILY_API_KEY = "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"
