# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "applyo-worker"
main = "src/index.ts"
compatibility_date = "2025-10-11"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "applyo-db"
database_id = "f1c25a1c-ba2f-46e7-89f4-a6d632690141"
migrations_dir = "drizzle"
remote = true

[[durable_objects.bindings]]
name = "Prospects"
class_name = "Prospects"

[[durable_objects.bindings]]
name = "Profiler"
class_name = "Profiler"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Prospects"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["Profiler"]

# Secrets (use `wrangler secret put TAVILY_API_KEY` to set)
# TAVILY_API_KEY = "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"
